@echo off
chcp 65001 >nul
title Local RAG Environment Check
echo Local RAG Environment Check
echo This script only reads system information
echo.
powershell.exe -NoLogo -NoProfile -Command "$ErrorActionPreference='SilentlyContinue'; function Show([string]$Status,[string]$Name,[string]$Value){$color=switch($Status){'PASS'{'Green'}'WARN'{'Yellow'}'UNKNOWN'{'Magenta'}default{'Cyan'}}; Write-Host ('[{0}] {1}: {2}' -f $Status,$Name,$Value) -ForegroundColor $color}; $os=Get-CimInstance Win32_OperatingSystem; $computer=Get-CimInstance Win32_ComputerSystem; $cpu=Get-CimInstance Win32_Processor | Select-Object -First 1; $build=[Environment]::OSVersion.Version.Build; $arch=if($os.OSArchitecture){$os.OSArchitecture}elseif([Environment]::Is64BitOperatingSystem){'64-bit'}else{'32-bit'}; $win=if($os.Caption){$os.Caption}elseif($build -ge 22000){'Windows 11'}else{[Environment]::OSVersion.VersionString}; $status=if(($win -match 'Windows 11' -or $build -ge 22000)-and $arch -match '64'){'PASS'}else{'WARN'}; Show $status 'Windows' ($win+' '+$arch+' | Build '+$build); $cpuName=if($cpu.Name){$cpu.Name.Trim()}else{$env:PROCESSOR_IDENTIFIER}; $cores=if($cpu.NumberOfCores){[int]$cpu.NumberOfCores}else{0}; $threads=if($cpu.NumberOfLogicalProcessors){[int]$cpu.NumberOfLogicalProcessors}else{[Environment]::ProcessorCount}; $status=if(-not $cores){'UNKNOWN'}elseif($cores -ge 4 -and $threads -ge 8){'PASS'}else{'WARN'}; $coreText=if($cores){$cores}else{'Unknown'}; Show $status 'CPU' ($cpuName+' | '+$coreText+' cores | '+$threads+' threads'); $ram=if($computer.TotalPhysicalMemory){[math]::Round($computer.TotalPhysicalMemory/1GB,1)}else{$null}; $status=if($null -eq $ram){'UNKNOWN'}elseif($ram -ge 15){'PASS'}else{'WARN'}; $value=if($null -eq $ram){'Unable to read'}else{$ram.ToString()+' GB'}; Show $status 'Memory' $value; $drive=New-Object System.IO.DriveInfo($env:SystemDrive); $free=if($drive.IsReady){[math]::Round($drive.AvailableFreeSpace/1GB,1)}else{$null}; $status=if($null -eq $free){'UNKNOWN'}elseif($free -ge 50){'PASS'}else{'WARN'}; $value=if($null -eq $free){'Unable to read'}else{$free.ToString()+' GB'}; Show $status 'Free disk on system drive' $value; $virt=$cpu.VirtualizationFirmwareEnabled; $status=if($null -eq $virt){'UNKNOWN'}elseif($virt){'PASS'}else{'WARN'}; $value=if($null -eq $virt){'Unable to read'}else{$virt.ToString()}; Show $status 'Virtualization enabled' $value; if(Get-Command wsl.exe){Show 'PASS' 'WSL' 'Installed and available'}else{Show 'INFO' 'WSL' 'Not installed or unavailable'}; $docker=docker.exe version --format '{{.Server.Version}}' 2>$null; if($LASTEXITCODE -eq 0 -and $docker){Show 'PASS' 'Docker Engine' $docker}else{Show 'INFO' 'Docker Engine' 'Not installed or not running'}; $gpu=nvidia-smi.exe --query-gpu=name,memory.total --format=csv,noheader 2>$null; if($LASTEXITCODE -eq 0 -and $gpu){Show 'PASS' 'NVIDIA GPU' ($gpu -join ' | ')}else{Show 'INFO' 'NVIDIA GPU' 'Not detected | GPU is optional'}"
echo.
echo Recommended baseline
echo Windows 11 ^| 4 cores 8 threads ^| 16 GB RAM ^| 50 GB free SSD ^| Virtualization enabled
echo.
echo Press any key to close this window
pause >nul

